name: Notify on Push to Main

on:
  push:
    branches:
      - main

jobs:
  send_email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.youremailprovider.com
          server_port: 587
          username: ${{secrets.}}
          password: ${{secrets.}}
          subject: 'Code pushed to main branch'
          to: ${{secrets.
          from: ${{secrets.
          body: 'Code has been pushed to the main branch of the repository.'
