name: push notification

on:
  push:
    branches:
      - main

jobs:
  send_email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Email Notification
        uses: dawidd6/action-send-mail@v2
        with:

          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: 'Code pushed to main branch'
          to: ${{secrets.TO}}
          from: ${{secrets.FROM}}
          body: 'Code has been pushed to the main branch of the repository.'

      - name: Print Secrets
        run: |
          echo "EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}"
          echo "EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}"
          echo "TO: ${{ secrets.TO }}"
          echo "FROM: ${{ secrets.FROM }}"
